//
//  CoworkPluginService.swift
//  NeuralJack
//

import AppKit
import Foundation

/// Generates a Cowork-compatible plugin package for importing migrated projects into Claude.
final class CoworkPluginService {
    func generatePlugin(
        packages: [ClaudeProjectPackage],
        outputDirectory: URL
    ) throws -> URL {
        let accessing = outputDirectory.startAccessingSecurityScopedResource()
        defer { if accessing { outputDirectory.stopAccessingSecurityScopedResource() } }

        let pluginDir = outputDirectory.appendingPathComponent("cowork-plugin", isDirectory: true)
        let tasksDir = pluginDir.appendingPathComponent("tasks", isDirectory: true)
        try FileManager.default.createDirectory(at: tasksDir, withIntermediateDirectories: true)

        let n = packages.count
        let dateStr = formatDate(Date())

        try writePLUGINmd(to: pluginDir, packageCount: n, packages: packages)
        for (index, pkg) in packages.enumerated() {
            let taskFile = tasksDir.appendingPathComponent(
                String(format: "%02d-setup-%@.md", index + 1, sanitizeForFilename(pkg.name)),
                isDirectory: false
            )
            try writeTaskFile(for: pkg, to: taskFile)
        }
        try writeREADMEmd(to: pluginDir, packages: packages, dateStr: dateStr)

        NSWorkspace.shared.selectFile(nil, inFileViewerRootedAtPath: pluginDir.path)
        return pluginDir
    }

    private func writePLUGINmd(to dir: URL, packageCount: Int, packages: [ClaudeProjectPackage]) throws {
        let stepLines = buildPluginSteps(packages: packages)
        let content = """
        ---
        name: NeuralJack Import
        description: Import \(packageCount) ChatGPT project\(packageCount == 1 ? "" : "s") into Claude.ai
        version: 1.0
        ---

        # NeuralJack Import Plugin

        This plugin was generated by NeuralJack to help you set up
        your migrated ChatGPT projects in Claude.

        ## What it does
        Opens claude.ai and creates \(packageCount) Claude Project\(packageCount == 1 ? "" : "s") with:
        - Project names and instructions from your ChatGPT history
        - Your Memory Core as project context

        ## How to use
        1. Open Claude Desktop → switch to Cowork tab
        2. Install this plugin (drag PLUGIN.md into Cowork plugins)
        3. Type /neuraljack-import to run

        /neuraljack-import:
          description: Set up all \(packageCount) migrated ChatGPT project\(packageCount == 1 ? "" : "s") in Claude
          steps:
        \(stepLines)
        """
        try content.write(to: dir.appendingPathComponent("PLUGIN.md"), atomically: true, encoding: .utf8)
    }

    private func buildPluginSteps(packages: [ClaudeProjectPackage]) -> String {
        var lines: [String] = ["    - Open https://claude.ai/projects in Chrome"]
        for (index, pkg) in packages.enumerated() {
            let taskName = String(format: "%02d-setup-%@.md", index + 1, sanitizeForFilename(pkg.name))
            lines.append("    - Create project \"\(pkg.name)\" and follow tasks/\(taskName)")
        }
        return lines.joined(separator: "\n")
    }

    private func writeTaskFile(for pkg: ClaudeProjectPackage, to url: URL) throws {
        let instructionsContent = (try? String(contentsOf: pkg.projectInstructionsFile, encoding: .utf8)) ?? ""
        let conversationPaths = pkg.conversationFiles.map { "- \($0.lastPathComponent)" }.joined(separator: "\n")
        let content = """
        # Set up project: \(pkg.name)

        Go to https://claude.ai/projects and create a new project with:

        Name: \(pkg.name)

        Project Instructions:
        \(instructionsContent)

        Then upload these files to the project knowledge base:
        \(conversationPaths)
        - memory-core.md
        """
        try content.write(to: url, atomically: true, encoding: .utf8)
    }

    private func writeREADMEmd(to dir: URL, packages: [ClaudeProjectPackage], dateStr: String) throws {
        let projectList = packages.map { "- \($0.name) (\($0.conversationCount) conversation\($0.conversationCount == 1 ? "" : "s"))" }.joined(separator: "\n")
        let n = packages.count
        let content = """
        # How to use this Cowork plugin

        ## Requirements
        - Claude Desktop app (claude.ai/download)
        - Paid Claude subscription (Pro, Max, Team, or Enterprise)
        - Claude in Chrome extension installed

        ## Steps
        1. Open Claude Desktop
        2. Click the Cowork tab
        3. Drag the PLUGIN.md file into Cowork to install it
        4. Make sure Claude in Chrome is active in your browser
        5. Type: /neuraljack-import
        6. Cowork will set up all \(n) project\(n == 1 ? "" : "s") automatically

        ## What gets created
        \(projectList)

        Generated by NeuralJack on \(dateStr)
        """
        try content.write(to: dir.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
    }

    private func sanitizeForFilename(_ name: String) -> String {
        let invalid = CharacterSet(charactersIn: "/\\:*?\"<>|")
        var result = name.unicodeScalars
            .map { invalid.contains($0) ? "-" : String($0) }
            .joined()
        result = result.trimmingCharacters(in: .whitespaces).replacingOccurrences(of: " ", with: "-")
        return result.isEmpty ? "project" : String(result.prefix(40))
    }

    private func formatDate(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateStyle = .long
        return f.string(from: date)
    }
}
